"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///nextcloud/views.py:42:19:42:25""]].","/nextcloud/directory_watcher.py","78","31","78","39"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///nextcloud/views.py:42:19:42:25""]].","/nextcloud/directory_watcher.py","79","13","79","35"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///nextcloud/views.py:42:19:42:25""]].","/nextcloud/directory_watcher.py","81","31","81","40"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///api/views/user.py:42:29:42:29""]] flows to this location and may be exposed to an external user.","/api/views/user.py","44","29","44","47"
